name: Build GrapheneOS Kernel for Samsung Galaxy A50

on:
  workflow_dispatch:
    inputs:
      configuration:
        description: 'Configuration for building the kernel (e.g., device and flavor)'
        required: true

jobs:
  build_kernel:
    name: Build GrapheneOS Kernel for Samsung Galaxy A50
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Nix
        uses: cachix/install-nix-action@v17

      - name: Build Kernel
        run: |
          nix-build "https://github.com/danielfullmer/robotnix/archive/master.tar.gz" \
            --arg configuration '{ device="samsung-a50"; flavor="vanilla"; }' \
            -A img

      - name: Upload Kernel Image as Artifact
        uses: actions/upload-artifact@v2
        with:
          name: kernel_image
          path: result/boot.img
